language: java
sudo: true
dist: xenial
addons:
  postgresql: "12"
sonarcloud:
    organization: "alexbru"
    token:
      secure: "q33dgzE6a1ijajE/kJ1h8+886Yw6HZQ/As5h8hlicxOCr10f5PkmiPv2JpyVknx8oyd4Wo4UPintqw5PCdoGnK4hSGf5IMa/OtjjJ1FpqCQ/KugYEgflbxFSGO1O7b28TggTXt91krHI1gOCIrEpU59WfvQe9mqA1aPtI5ptAJaalwlSeLaW9KWA1Z0UUZyCrHLcq9H/SGhd4HSh7arcH0iFsXxJcfq5EXNT2WE8DOjyW6sFQyomORX72pxGLHObtGZFlEVDhQb51/1kozfgjebjsIk87zo3EiSYJRM0QRgDye1u7DBbvEqBnT9M+TJNtHTXxiEMIAMc/COfBkulUgxmDh6t7TJzZcVPMhOOBGwr67XzRCAM3ayPgfIxpNqIyP8CchuRJhcG4D4UTNAQeBia7dOw3F4GhlpV3plIuui6d4qSI+O7ZVQmXx3U+MaSdn/7q2DqqCN3Ceux04MDKvdEI19ymAA8Vwe6MaE2rrYpVpBR3PXtd6K+hSSy/fnK2XOzvzMMY5ltubfcmjRmhMB0tY9LR2RyNyBb3oaAGvOE3SKqlQvnjeDKvCFPtFG5GR1pfpxDvxdNrMhzDngOT3PYZw1iXyapB3kzcLDsPJ4AZk9M6CqDBaNtNPfvXRGPbPBq+KP/zbUjcnnD0p1Rkt/20l9gPYK1IqpRoSELTOU=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=OleksandrBrukhalskyi_petclinic

before_install:
  - chmod +x mvnw
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11
  - sudo mkdir /var/pgsql_socket
  - sudo ln /tmp/.s.PGSQL.5432 /var/pgsql_socket/
  - sudo systemctl start postgresql
before_script:
  - psql -c 'create database petclinic' -U postgres
services:
  - postgresql
env:
  global:
    - PGUSER=postgres
    - PGPORT=5432