language: java
sudo: true
dist: xenial
addons:
  postgresql: '11'
  apt:
    packages:
    - postgresql-client-11
    - postgresql-server-dev-11
sonarcloud:
  organization: alexbru
  token:
    secure: cHmhan91J2X9H02qTC9Z2ahEgTqtM3NZnfLT+FqhAfQllmnIlDBDi/AGgdCOvVd9F73SvGP3pjJ2UHrx6P6EuPFwVp/46eQ6gAYvAxtdWWr2hOxbCHMusnxuby1+Yl/JLdCtUieAKNZwzjDLGUp3myoq0lDERQ+s6xferYatlaKYpz/Lzw5FBdymyoW4ZQXNe/yxF9mMivvJ5hTNovuZ66EGWkF6yBjPm0Dm0yoyto3SYXkAGYfBWlJje9q66FnnatGyOjpx+Y7ZXIExxTWhCLi4Mk/Mmt3WSFNEm2pwMSTw+cWmnrY8B5iRhs4XhdrKr4TyTwuST/Qf5M5R8ptylCf6cWhiKU+foOJGBaShIqJQR85prSXRE99NwwsvwkEZNnQI3g3T1qyLzz25mIcVipWaequYRDOUrf0JlMF8ZsxNeBAikuS83RtBY/gU/jqRtNnqV+J6rTmDZGReVHJnVPxlBzROfYRD2FnFUbNflbby85vDoJlMPZhdaZx6IOZ/6nsg8Zv48015+BZR5FfoylkpdsLYFo4F1QSNhnQbkJnsmCipVttTpR4iZ6OXERN2m6bwdv4Zt0yuPIRoNs5bQevFJWQUIx4FdFurRiBQ3LwbV7XvtB4tZGVUnvdSGHBtG3SzjgQe1NEYoXuvcpWlJy9zroswmYQ/Tn+DVtuTQ/c=
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Pcoverage
  -Dsonar.projectKey=OleksandrBrukhalskyi_petclinic -Dsonar.organization=alexbru -Dsonar.host=https://sonarcloud.io
  -Dsonar.login=058797318462deec7373ad4546a872cdfff8cea0
before_install:
- chmod +x mvnw
- sudo systemctl start postgresql
- sudo find /tmp/ -name .s.PGSQL.5432
before_script:
- psql -c 'create database petclinic;' -U postgres
services:
- postgresql
env:
  global:
  - PGUSER=postgres
  - PGPORT=5432
  - secure: cHmhan91J2X9H02qTC9Z2ahEgTqtM3NZnfLT+FqhAfQllmnIlDBDi/AGgdCOvVd9F73SvGP3pjJ2UHrx6P6EuPFwVp/46eQ6gAYvAxtdWWr2hOxbCHMusnxuby1+Yl/JLdCtUieAKNZwzjDLGUp3myoq0lDERQ+s6xferYatlaKYpz/Lzw5FBdymyoW4ZQXNe/yxF9mMivvJ5hTNovuZ66EGWkF6yBjPm0Dm0yoyto3SYXkAGYfBWlJje9q66FnnatGyOjpx+Y7ZXIExxTWhCLi4Mk/Mmt3WSFNEm2pwMSTw+cWmnrY8B5iRhs4XhdrKr4TyTwuST/Qf5M5R8ptylCf6cWhiKU+foOJGBaShIqJQR85prSXRE99NwwsvwkEZNnQI3g3T1qyLzz25mIcVipWaequYRDOUrf0JlMF8ZsxNeBAikuS83RtBY/gU/jqRtNnqV+J6rTmDZGReVHJnVPxlBzROfYRD2FnFUbNflbby85vDoJlMPZhdaZx6IOZ/6nsg8Zv48015+BZR5FfoylkpdsLYFo4F1QSNhnQbkJnsmCipVttTpR4iZ6OXERN2m6bwdv4Zt0yuPIRoNs5bQevFJWQUIx4FdFurRiBQ3LwbV7XvtB4tZGVUnvdSGHBtG3SzjgQe1NEYoXuvcpWlJy9zroswmYQ/Tn+DVtuTQ/c=
