language: java
sudo: true
dist: trusty
jdk: oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=OleksandrBrukhalskyi_petclinic
services:
  - postgresql
before_script:
  - psql -c 'create database petclinic;' -U postgres
env:
  global:
    - PGUSER=postgres
    - PGPORT=5432