language: java
sudo: true
dist: xenial
addons:
  postgresql: "11"
  apt:
    packages:
      - postgresql-client-11
      - postgresql-server-dev-11
sonarcloud:
    organization: "alexbru"
    token:
      secure:  $SONAR_TOKEN # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  -  mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=OleksandrBrukhalskyi_petclinic -Dsonar.organization=alexbru -Dsonar.host=https://sonarcloud.io -Dsonar.login=d4a61732ecc7b8523b6c35f08fdd7171d6c368e0

before_install:
  - chmod +x mvnw
  - sudo systemctl start postgresql
  - sudo find /tmp/ -name .s.PGSQL.5432
before_script:
  - psql -c 'create database petclinic;' -U postgres
services:
  - postgresql
env:
  global:
    - PGUSER=postgres
    - PGPORT=5432