language: java
sudo: true
dist: xenial
addons:
  postgresql: "11"
  apt:
    packages:
      - postgresql-client-11
      - postgresql-server-dev-11
sonarcloud:
    organization: "alexbru"
    token:
      secure: "DW8Z/u3lFFVGkjBcls9fGwYlQNRbIpjJS38Ejjq7RN5Qj9PKsPMuPIIacsKwM3tHJ7A/cBvDXAafOk/RcN2nXvke4tP/mgN7SZEgPJGx8s5fv9C3NaOQIg2WzaJcazmqlX1mpAzinHJ9l3m8WVgLgAnkEBP5aROAP2VuKcobcKjEnHg83AoiLny9p4O1TR8iS0cUbxbM+hwOQqRUwA8maN+mjBdx3B1jCnXzHQpww4RMZ6RbNz3QckQ2VLIv7a/ryq8n7QUnfrzPwRHiES8M3RVkvNUf52NLwqzwu5lqPbwEyREg68MgzvVRH7rzR8j9AAiqf2GMy+f0cSI/CyYROBW6JGy/7PY5V6Ir89HW2vmSiBUGvNJDn4B2HohJgL1rcWMEnb6vSJYQYryA239Th8N4Z5kHAh0Li5DJQ1lyOlvy2AwAbofvHJz2iao2hvnJixIU3SbIxg/UZkjKprEVPv9pjQr1PTR5UKamE0NZYdMIKYyZ05WidMtZfRYRona+OCGKZmk5wfnv6j/ueZNRYzy9sdDnfzzfkWkYGAge7fQM5aapHwu1/JFgN7jnvqEyqr8E5Ya1OEzvUH/ffufDOVboZ2klwS9ZDT+Sxc1/N+BELrSv2J4BacVlwzMfRzjjZmK2pKg9AXJK7sZODxOewcAh12iXkWWZqvKu3E1FyIU=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=OleksandrBrukhalskyi_petclinic

before_install:
  - chmod +x mvnw
  - sudo systemctl start postgresql
  - sudo find /tmp/ -name .s.PGSQL.5432
before_script:
  - psql -c 'create database petclinic;' -U postgres
services:
  - postgresql
env:
  global:
    - PGUSER=postgres
    - PGPORT=5432